development:
  return_url: http://localhost:3000/success
  cancel_url: http://localhost:3000/cancel
  ipn_url: http://localhost:3000/ipn

test:
  return_url: http://localhost:3000/success
  cancel_url: http://localhost:3000/cancel
  ipn_url: http://localhost:3000/ipn

production:
  return_url: http://igorribeirolima.com.br:3000/success
  cancel_url: http://igorribeirolima.com.br:3000/cancel
  ipn_url: http://igorribeirolima.com.br:3000/ipn